# Generated by Django 3.1 on 2022-08-22 21:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_car', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'db_table': 'carpeta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_gal', models.CharField(max_length=100, unique=True)),
                ('descripcion_gal', models.CharField(max_length=100)),
                ('imagen_gal', models.ImageField(upload_to='Galerias/%Y/%m', verbose_name='Galeria')),
                ('estado_gal', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('url_gal', models.URLField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'db_table': 'galeria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.TextField()),
                ('imagen_intro', models.ImageField(upload_to='Inicio/introduccion/', verbose_name='Imagen introduccion')),
                ('mision', models.TextField()),
                ('imagen_mision', models.ImageField(upload_to='Inicio/mision/', verbose_name='Imagen Mision')),
                ('vision', models.TextField()),
                ('imagen_vision', models.ImageField(upload_to='Inicio/vision/', verbose_name='Imagen Vision')),
                ('resenia', models.TextField()),
                ('imagen_resenia', models.ImageField(upload_to='Inicio/resenia/', verbose_name='Imagen Resenia')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'institucion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pro', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Slug')),
                ('descripcion_pro', models.CharField(max_length=100)),
                ('contenido_pro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen_pro', models.ImageField(upload_to='Programa/%Y/%m/', verbose_name='Programa')),
                ('estado_pro', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('fechacreacion_pro', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subcarpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sub', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Subcarpeta',
                'verbose_name_plural': 'Subcarpetas',
                'db_table': 'subcarpeta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dir', models.CharField(max_length=100, unique=True)),
                ('descripcion_dir', models.CharField(max_length=100)),
                ('archivo_dir', models.FileField(upload_to='Directorios/%Y/%m', verbose_name='Directorio')),
                ('contenido_dir', models.TextField(blank=True, null=True)),
                ('fechacreacion_dir', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fk_id_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carpeta')),
            ],
            options={
                'verbose_name': 'Directorio',
                'verbose_name_plural': 'Directorios',
                'db_table': 'directorio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carpeta_Subcarpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carpeta')),
                ('fk_id_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.subcarpeta')),
            ],
            options={
                'verbose_name': 'Carpeta_Subcarpeta',
                'verbose_name_plural': 'Carpetas_Subcarpetas',
                'db_table': 'carpeta_subcarpeta',
                'ordering': ['id'],
                'unique_together': {('fk_id_car', 'fk_id_sub')},
            },
        ),
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asa', models.CharField(max_length=100, unique=True)),
                ('descripcion_asa', models.CharField(max_length=100)),
                ('archivo_asa', models.FileField(upload_to='Asambleas/%Y/%m', verbose_name='Asamblea')),
                ('contenido_asa', models.TextField(blank=True, null=True)),
                ('fechacreacion_asa', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fk_id_asa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carpeta')),
            ],
            options={
                'verbose_name': 'Asamblea',
                'verbose_name_plural': 'Asambleas',
                'db_table': 'asamblea',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_arch', models.CharField(max_length=100, unique=True)),
                ('descripcion_arch', models.CharField(max_length=100)),
                ('archivo_arch', models.FileField(upload_to='Archivos/%Y/%m', verbose_name='Archivo')),
                ('fechacreacion_arch', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('contenido_arch', models.TextField(blank=True, null=True)),
                ('fk_id_carsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carpeta_subcarpeta')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contadorvistasdirectorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorio_con', models.IntegerField(default=0)),
                ('estado_con', models.BooleanField(default=True, verbose_name='Contador/No contador')),
                ('fk_id_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carpeta')),
            ],
            options={
                'verbose_name': 'Contadorvistasdirectorio',
                'verbose_name_plural': 'Contadorvistasdirectorios',
                'db_table': 'contadorvistasdirectorio',
                'ordering': ['id'],
                'unique_together': {('fk_id_con',)},
            },
        ),
        migrations.CreateModel(
            name='Contadorvistasasamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asamblea_cont', models.IntegerField(default=0)),
                ('estado_cont', models.BooleanField(default=True, verbose_name='Contador /No contador')),
                ('fk_id_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.carpeta')),
            ],
            options={
                'verbose_name': 'Contadorvistasasamblea',
                'verbose_name_plural': 'Contadorvistasasambleas',
                'db_table': 'contadorvistasasamblea',
                'ordering': ['id'],
                'unique_together': {('fk_id_cont',)},
            },
        ),
    ]
