# Generated by Django 3.1 on 2022-08-22 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ani', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Anio',
                'verbose_name_plural': 'Anios',
                'db_table': 'anio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Anios_Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivero.anios')),
            ],
            options={
                'verbose_name': 'Anio_Tema',
                'verbose_name_plural': 'Anios_Temas',
                'db_table': 'anio_tema',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tem', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'temas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_doc', models.FileField(upload_to='Archivero/%Y/%m', verbose_name='Documento')),
                ('fechacreacion_doc', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('contenido_doc', models.TextField(blank=True, null=True)),
                ('fk_id_atem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivero.anios_temas')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='anios_temas',
            name='fk_id_tem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivero.temas'),
        ),
        migrations.AlterUniqueTogether(
            name='anios_temas',
            unique_together={('fk_id_ani', 'fk_id_tem')},
        ),
    ]
